# Generated by Django 4.2.7 on 2023-11-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('publication', models.PositiveIntegerField(verbose_name='Год издания')),
                ('isbn', models.CharField(max_length=13)),
            ],
        ),
    ]
